juxt/site

- src/juxt/site/alpha/function.clj
- src/juxt/site/alpha/handler.clj
Currently passes a context map to a multi-method, considering registering into
mutable state as an alternative.
> Add service-function implementation

- bin/site
- src/juxt/apex/alpha/representation_generation.clj
- src/juxt/site/alpha/openapi.edn
- Use `as-str` for rules also in `bin/site`
- Unnest eql/pull queries implicitly
- Convert limiting-clauses in site api
> Small changes for rules

- src/juxt/mail/alpha/mail.clj
- src/juxt/site/alpha/handler.clj
- Use a function to log sns, ses stubs in development
- Add error logging to message dispatching
- Merge remaining options from config into request map
> Add separation between sns/ses sending

- src/juxt/site/alpha/resources.clj
This allows us to post resources with a regex string, we use #regex as the #"..." syntax is not a part of edn.
(Edn Regex Issue covered in more detail here https://groups.google.com/g/clojure/c/htOjm8tu3-o/m/Y7spvfXtAQAJ)
> Add reader for regexes

- README.adoc
This PR fixes the license being rendered as a code block in README.
> Fix formatting of the license in README

- src/juxt/site/alpha/graphql.clj
@armincerf helped me figure out why the types weren't being automatically added onto the entities anymore.
I've added them back under the condition there's not a type already defined on the entity.
If it's a design decision that they aren't there anymore feel free to close this
> Default entity type when not provided

- src/juxt/site/alpha/debug.clj
This fixes the issue I ran into earlier. If you rather fix the issue by more carefully examining where we set contents of `ex-info` feel free to close.
> Fix JSON encoding when response contains a java.util.regex.Matcher

- README.adoc
* added specific section for macOS (libcrypto.dylib not found)
* fixed typo (coreutils installs greadlink and not linkread)
> added specific section for macOS 

- README.adoc
There is a single character typo in readme in block delimiters which inverts all of the content below.
See [readme on master](https://github.com/juxt/site#macos--1015) vs [readme on the fixed branch](https://github.com/msladecek/site/tree/fix-readme-pre-blocks#macos--1015)
> fix mismatched block delimiters in readme

- opt/login-form/install
- opt/login-form/login-form-rule.edn
- opt/login-form/login.html
- opt/login-form/resources.edn
- opt/login-form/unauthorized.html
- src/juxt/pass/alpha/authentication.clj
- src/juxt/site/alpha/selmer.clj
- src/juxt/site/alpha/templating.clj
The key changes are:
- Added logic to allow `::site/template-model` to be a symbol so that we can define a function that accepts the request, extracts the requested URL and injects it into the template to allow the user to be redirected back once they've authenticated
- Changed `POST /_site/login` to extract the redirect URL from the `_query` value and then to also parse it to get only the `redirect` value (i.e. go to `/swagger-ui/index.html` not `redirect=/swagger-ui/index.html`)
- Added the HTML page files and XTDB entity definitions
> Add login-form module

- test/juxt/site/handler_test.clj
Fix test by matching `send-mail!`'s number of arguments
> Fix triggers-test send-mail! number of arguments

- .gitignore
- deps.edn
- src/juxt/apex/alpha/helpers.clj
Added `:coverage` alias to `deps.edn`. This can be specified when running kaocha along with `--plugin cloverage` to generate a coverage report.
(It is possible to generate a coverage report using the alias and cloverage directly, but this will ignore the configuration in `tests.edn`)
Added target to `.gitignore` because by default a html report is generated there.
Also fixed `helpers.clj` which did not have a renamed function applied to it. This namespace does not appear to be used and could be removed at a later point.
> Add test coverage plugin

- test/juxt/demo.clj
- test/juxt/site/demo_test.clj
This was caused by the `authorize-application` permission being overwritten by the `issue-access-token` permission.
Updated the `:xt/id` to no longer overwrite and re-enabled the `put-application` and `authorize-application` steps in the `demo-test`
> Fix issue with authorize-application in demo-test

- test/juxt/pass/authorization_test.clj
- tests.edn
https://github.com/juxt/site/commit/33215da98daed9c4478f43a30c20383192ad1d9d changed the behavior to throw when an action could not be found.
Also the person and action ID were the wrong way around.
Now re-enabled the tests in tests.edn because they all pass.
> Fix issue with authorization test exception

- test/juxt/site/graphql_test.clj
Fixes a broken test that is currently causing the CI build to fail.
```
FAIL in juxt.site.graphql-test/mutation-test (graphql_test.clj:280)
Expected:
{:name "Malcolm Sparks", :juxt.site/type "Person", :xt/id "https://example.org/persons/mal"}
Actual:
{:name "Malcolm Sparks",
:juxt.site/type "Person",
:xt/id "https://example.org/persons/mal",
+:_siteCreatedAt "2022-05-26T13:28:50.568652Z"}
```
> Ignore :_siteCreateAt when verifying mutation

- deps.edn
- src/juxt/site/alpha/graphql.clj
- src/juxt/site/alpha/graphql_resolver.clj
- src/juxt/site/alpha/handler.clj
- src/juxt/site/alpha/repl.clj
- test/juxt/site/graphql_test.clj
Best to view diffs by commit since one commit is purely indentation (we should probably do something about not having a ci step to enforce indentation rules)
- updates xt to 1.21
- adds the ability to use {{subject}} in the q directive
NOTE: you will need to delete xt indexes before you start the process again, i.e `rm -r db/idxs`
> Merge generic updates from client side-site

- deps.edn
- src/juxt/site/alpha/debug.clj
- src/juxt/site/alpha/graphql.clj
- src/juxt/site/alpha/handler.clj
- src/juxt/site/alpha/rules.clj
- test/juxt/site/graphql_test.clj
Given the following `schema.graphql`:
```
schema {
query: Query
mutation: Mutation
}
type Query { person: Person }
input PersonInput {
name: String!
id: ID
}
type Person {
id: ID
name: String!
}
type Mutation {
addPerson(
person: PersonInput
): Person @site(
validation: {
person: "[:map [:id {:optional true} :any] [:name [:string {:min {{minlen}} :max 20}]]]"
}
)
}
```
site would perform a validation against full-featured [`malli`](https://github.com/metosin/malli) schema. [`selmer`](https://github.com/yogthos/Selmer) templating is possible although it requires some effort to move it out to system level.
> Make `validation` site directive possible

- src/juxt/pass/alpha/openid_connect.clj
To ensure that user oauth information can be permissioned separately from the user entity they are now stored separately.
> Change oauth user query to use OAuthCredentials

- src/juxt/site/alpha/graphql.clj
Providing a mutation in a graphql schema for example
```
type Mutation {
updateMovie(
id: ID!
name: String!
showing: Boolean
): Movie @site(mutation: "update")
}
```
and executing this mutation in graphiql setting `showing` to `true` works, but setting `showing` to `false` does not change the value to false.
There is some code duplication that could do with refactoring, but this PR fixes it and hopefully helps by pointing out where this case breaks down.
> fix issue with mutation of false booleans

- deps.edn
- src/juxt/pass/alpha/openid_connect.clj
- src/juxt/pass/alpha/session.clj
- src/juxt/site/alpha/init.clj
Add retry behaviour to network calls during OpenID connect authentication. Also change call to token endpoint to use form parameters rather than a JSON body as AWS Cognito only supports form parameters.
To enable a user to login using this flow a 'OAuthCredentials' entity must be created with a `:juxt.pass.jwt/iss` and `:juxt.pass.jwt/sub` pair along with the ':juxt.pass.alpha/user' id of the user.
> Add diehard resilience to OpenID connect auth and AWS Cognito support

- dev/user.clj
- src/juxt/apex/alpha/helpers.clj
This was likely related to my workflow only, but some of the requires I fixed generated "already defined" exceptions while trying to reload namespaces at the repl. There was also an apex namespace that couldn't work because it refers to non existing functions. Tests are green and site-server up and running.
> Fixed errors in reloading namespaces from REPL

- src/juxt/site/alpha/watcher.clj
File watcher was broken, every time new schema was added to the graphql schema directory, schema id was created incorrectly.
Root cause of this was that file watcher callback function expected new file path to always be absolute, but it was relative, at least on my env when I exactly followed site tutorial.
Adding check whether new file path is truly absolute and conditionally extracting relative-path only if this check is true fixes the issue.
> Fix file watcher function

- src/juxt/site/alpha/graphql.clj
- test/juxt/site/graphql_test.clj
Added evict-cascade mutation functions. 
Evict-cascade mutation evicts entity and all linked entities linked by 'casadeKey' (cascadeKey mutation attribute is required)
Delete-cascade mutation deletes entity and all linked entities linked by 'casadeKey' (cascadeKey mutation attribute is required)
The usage of evict-cascade and delete-cascade mutations is also demonstrated in tests.
> Evict cascade and delete cascade mutation function

- bin/site-server-bootstrap
- src/juxt/pass/alpha/openid_connect.clj
- src/juxt/site/alpha/init.clj
- src/juxt/site/alpha/openapi.edn
- src/juxt/site/alpha/repl.clj
- test/juxt/pass/openid_connect_test.clj
- test/juxt/pass/openid_connect_test_utils.clj
- test/juxt/test/util.clj
This changes are necessary to close issue [#328](https://github.com/juxt/excel/issues/328) of [juxt/excel](https://github.com/juxt/excel/).
The most significant changes are:
- Change `/_site/user` endpoint to return data when user has no `UserRoleMapping` entities associated with them (outer join)
- Change OAuth flow to create/update `User` entities on successful auth and update associated `UserRoleMapping`
- Add Tests for the OAuth flow code, specifically the login and callback endpoints
> Oauth update user and associated roles

- src/juxt/mail/alpha/mail.clj
Without this change merge-with-flatten can results in list within a map that contains multiple of the same value. This is undesirable as it is being used to return a list of email addresses to receive a message.
> Ensure merge-with-flatten returns distinct values

- src/juxt/mail/alpha/mail.clj
clojure.string/replace expects the result of the replacement function to return a string, or a value that can be cast to a string. To prevent class cast exceptions where the object cannot be cast to a string str is called to call .toString() on all returned objects. Specifically, this allows numeric values to be templated. This is needed to allow the result of the `max` aggregate function to be templated correctly, as it returns a long.
Also, change crux aggregate function distinct-string-list to sorted-string-list. Function must sort the values into a logical order.
> Fix mail templating of non-strings
